kind: Deployment
apiVersion: apps/v1
metadata:
  name: codeserver
  labels:
    app: codeserver
    part-of: codeserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeserver
      part-of: codeserver
  template:
    metadata:
      labels:
        app: codeserver
        part-of: codeserver
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
      containers:
      - name: codeserver
        image: lscr.io/linuxserver/code-server:4.0.1
        ports:
        - name: codeserver
          containerPort: 8443
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Paris"
        - name: DOCKER_MODS
          value: "linuxserver/mods:code-server-golang|linuxserver/mods:universal-git|linuxserver/mods:code-server-zsh|linuxserver/mods:code-server-python3"
        readinessProbe:
          httpGet:
            path: /
            port: codeserver
          initialDelaySeconds: 115
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: codeserver
          initialDelaySeconds: 125
          periodSeconds: 20
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 700Mi
        volumeMounts:
        - name: codeserver
          mountPath: /config
      volumes:
      - name: codeserver
        persistentVolumeClaim:
          claimName: codeserver
